apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dvwa
  labels:
    app: web-dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dvwa
  template:
    metadata:
      labels:
        app: web-dvwa
    spec:
      containers:
      - name: web-dvwa
        image: raniasaleh/web-dvwa
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web-dvwa
---
apiVersion: v1
kind: Service
metadata:
  name: web-dvwa
spec:
  selector:
    app: web-dvwa
  ports:
  - protocol: "TCP"
    port: 80
    nodePort: 30001
  type: NodePort
---
